/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_LoadJni */

#ifndef _Included_jni_LoadJni
#define _Included_jni_LoadJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_LoadJni
 * Method:    get
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_LoadJni_get
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
